provider: aws
service: app

custom:
  serverlessChatgpt:
    schemaVersion: string
    nameForHuman: string
    nameForModel: string
    descriptionForHuman: string
    descriptionForModel: string
    apiUrl: string
    logoUrl: string
    contactEmail: string
    legalInfoUrl: string

functions:
  hello:
    handler: handler.todo
    events:
      - httpApi:
          method: GET
          path: /todo

    serverlessChatgptFunction:
      operationId: get from some aws id
      summary: go to description
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      type: string
                    description: The list of todos.

plugins:
  - serverless-chatgpt